version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    - "16632:5432"

  wildfly:
    build: .
    depends_on:
      - db
    ports:
    - "8080:8080"